apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
spec:
  type: NodePort
  selector:
    app: devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007 # Fixed port for easy local access
